baseURL = 'https://mucleck.github.io/'
locale = 'en-us'
title = 'Un blog menos'
theme = 'book'

[menu]
[[menu.before]]
  name = 'Blog'
  pageRef = '/posts/'
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"

[params]
  BookTheme = 'light'
